repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [ --line-length=79 ]
        language_version: python3

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.1
    hooks:
      - id: pyupgrade
